# SPDX-FileCopyrightText: 2024 DESY and the Constellation authors
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "docs/**"
SPDX-FileCopyrightText = "DESY and the Constellation authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "subprojects/*.wrap"
SPDX-FileCopyrightText = "Meson WrapDB"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "cxx/constellation/core/external/md5.h"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
  "cxx/constellation/gui/Constellation.qrc",
  "cxx/constellation/gui/QCommandDialog.ui",
  "cxx/constellation/gui/QLogMessageDialog.ui",
  "cxx/constellation/gui/QResponseDialog.ui",
  "cxx/controllers/MissionControl/MissionControl.ui",
  "cxx/listeners/Observatory/Observatory.qrc",
  "cxx/listeners/Observatory/Observatory.ui",
]
SPDX-FileCopyrightText = "DESY and the Constellation authors"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = "cxx/constellation/gui/icons/**"
SPDX-FileCopyrightText = "Google Material Symbols"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "docs/etc/de.desy.constellation.metainfo.xml",
  "cxx/controllers/MissionControl/de.desy.constellation.missioncontrol.desktop",
  "cxx/listeners/Observatory/de.desy.constellation.observatory.desktop",
  "python/constellation/core/version_code_name",
]
SPDX-FileCopyrightText = "DESY and the Constellation authors"
SPDX-License-Identifier = "CC0-1.0"
