# SPDX-FileCopyrightText: 2025 DESY and the Constellation authors
# SPDX-License-Identifier: CC0-1.0

name: Formatting

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  format-python:
    name: Python Format Check (ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: format --diff

  format-cpp:
    name: C++ Format Check (clang-format)
    runs-on: ubuntu-latest
    container:
      image: gitlab.desy.de:5555/constellation/build-images/fedora-clang
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ignore git ownership warnings
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Run clang-format check
        run: |
          meson setup build -Dcxx_tests=enabled
          ninja -C build clang-format-check

  format-reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5

  format-codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Codespell Check
        uses: codespell-project/actions-codespell@v2
